modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="stellar_radiance"
version="1.2.1"
displayName="星·辉"
displayURL="https://b23.tv/hm8ia8d"
logoFile="logo.png"
credits="本mod大部分使用MCreator制作 - https://mcreator.net/about"
authors="lIl星虹流光lIl, MCreator"
description="你不是网易版的吗，你是怎么看见这个的？？"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.stellar_radiance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.stellar_radiance]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stellar_radiance]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

